### ISSUE TITLE
Abstract function for fillMissingness

### ISSUE THREAD

**Issue by tercer** [IQSS/PSI-Library#43]
There are different ways to call `fillMissingness()` (and `fillMissingness2d()`) depending on type, which presently leads to complex statements in mechanisms where we impute.  For example:
https://github.com/privacytoolsproject/PSI-Library/blob/ab872176be8a6b81555ec887d43bddb925f167af/R/mechanism-laplace.R#L22-L30

Instead, should just have one imputation function that deals with this and abstracts away these problems.

**Comment by globusharris** [comment]
Resolved in pull request #47

**Comment by globusharris** [comment]
Pull request #47 is merged.
