### ISSUE TITLE
Rewrite stability as a stand-alone mechanism

### ISSUE THREAD

**Issue by globusharris** [IQSS/PSI-Library#53]
Following histogram discussion on 6/12 with @MeganFantes, @vbalcer, and @Shoeboxam, we are altering how the stability mechanism is used in the histogram and changing it from a flag that's specific to the histogram statistic to a general mechanism.

**Comment by globusharris** [comment]
Should we have some sort of check to ensure that 1/delta << N and deny if not? Can we safely assume that N is public for this?

**Comment by MeganFantes** [comment]
Done, code pushed to `MF_AddingStabilityMechanism` branch. Working on other open issues concerning the histogram statistic before code review and merge.

**Comment by MeganFantes** [comment]
Currently there is a check in the stability mechanism to make sure delta < 1/N.
N is always assumed to be public, because it is necessary to instantiate the dpHistogram object.
