### ISSUE TITLE
Rederive check_histogram_n conditions

### ISSUE THREAD

**Issue by globusharris** [IQSS/PSI-Library#55]
The histogram statistic with the stability mechanism includes a function that checks whether or not the number of observations is sufficient to provide desired privacy and accuracy with the given parameters.

https://github.com/privacytoolsproject/PSI-Library/blob/3b3e0cd958e423d576ce6fb198652d24d5fbeaf2/R/utilities.R#L503-L532

Questions:
1. How were these conditions derived?
2. Are they actually checking that privacy is maintained or are they just checking that the accuracy is met? Conversation with @vbalcer indicated it may just be an accuracy check but want to be sure.

Related to #53 if this is a privacy issue that the stability mechanism needs to have a general check for.

**Comment by adamdavisonsmith** [comment]
This check does not appear necessary for the privacy analysis. I'm not sure exactly what it is verifying, but it is roughly that there are enough points that some bin has a chance of surviving the thresholding step.
