### ISSUE TITLE
Bins of NAs in histogram

### ISSUE THREAD

**Issue by globusharris** [IQSS/PSI-Library#58]
For Laplace mechanism, can't have a bin of NAs if using Laplace mechanism since then number of bins depends on the underlying data which is a privacy violation.

OR: we could always include an NA bin and always add noise to it?

**Comment by MeganFantes** [comment]
I think this question is answered differently for the different variable types:

**Logical:** For logical variables, if impute = FALSE in the dpHistogram object, then there is always an NA bucket added. If impute = TRUE, then there is never an NA bucket added.

**Numeric / integer:** for numeric or integer variables, the call to `fillMissing()` always fills NA buckets, so there is never an NA bucket.

**Categorical:** For categorical variables, the Laplace mechanism is only used when the user enters a vector of bins. So to answer this question, we just need to ask if we want to check if the input vector of bins contains NA or not, and if we want it to always have NA or not. In the stability mechanism, the bins are detected from the data, and NA values are not given their own bins, so the call to `fillMissing()` always fills NA buckets.

**Comment by globusharris** [comment]
Re categorical variables question: going to add impute flag to categorical data.
